<?xml version="1.0" encoding ="utf-8"?>

<!DOCTYPE Products [
	<!ELEMENT Products (Product*)>
	<!ELEMENT Product (Maker,Name,Price,Discount,Code)>
	<!ELEMENT Maker (#PCDATA)>
	<!ELEMENT Name (#PCDATA)>
	<!ELEMENT Price (#PCDATA)>
	<!ELEMENT Discount (#PCDATA)>
	<!ELEMENT Code (#PCDATA)>
	]>

<Products>
	<Product>
		<Maker>Dior</Maker>
		<Name>Raker Stick</Name>	
		<Price>42000</Price>
		<Discount>0.0</Discount>
		<Code>757</Code>
	</Product>

	<Product>
		<Maker>CHANNEL</Maker>
		<Name>ROUGE COCO</Name>	
		<Price>42000</Price>
		<Discount>0.0</Discount>
		<Code>99</Code>
	</Product>


</Products>